/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS = "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

export const SERVICES = {
  GET_ALL_SERVICES_TYPES: "SERVICES_GET_ALL_SERVICES_TYPES",
  LOAD_SERVICES_CATEGORY_LIST: "SERVICES_LOAD_SERVICES_CATEGORY_LIST",
  SET_SELECTED_SERVICE: "SERVICES_SET_SELECTED_SERVICE",
};

export const ORDERS = {
  LOAD_CUSTOMER_TOP_ORDERS: "ORDERS_LOAD_CUSTOMER_TOP_ORDERS",
  LOAD_ALL_ORDERS: "ORDERS_LOAD_ALL_ORDERS_LIST",
  SET_SELECTED_ORDER: "ORDERS_SET_SELECTED_ORDER",
};

export const INVOICES = {
  LOAD_ALL_INVOICES: "INVOICES_LOAD_ALL_INVOICES_LIST",
  SET_SELECTED_INVOICE: "INVOICES_SET_SELECTED_INVOICE",
};
export const ACCOUNT = {
  SET_ACCOUNT_DATA: "ACCOUNT_SET_ACCOUNT_DATA",
  SET_SELECTED_INVOICE: "INVOICES_SET_SELECTED_INVOICE",
};

export * from "./menu/actions";
export * from "./settings/actions";
export * from "./services/actions";
export * from "./orders/actions";
export * from "./account/actions";
